[versions]
agp = "8.7.3"
freefairAspectj = "8.10"
appCompat = "1.7.1"
material = "1.12.0"
multidex = "2.0.1"
xxPermissions = "20.0"
titleBar = "10.8"
toaster = "13.8"
easyHttp = "13.5"
okHttp = "4.12.0"
gsonFactory = "9.6"
gson = "2.11.0"
shapeView = "8.0"
glide = "4.16.0"
immersionBar = "3.2.2"
photoView = "2.3.0"
bugly = "4.1.9.3"
lottie = "6.4.0"
refreshLayout = "2.1.0"
timber = "5.0.1"
circleIndicator = "2.1.6"
mmkv = "1.3.5"
leakCanary = "2.14"
aspectj = "1.9.22"
greenDao = "3.3.0"
markwon = "4.6.2"
rsaUtils = "2.0.0"
bouncyCastle = "1.78.1"
utilCodex = "1.31.1"
groupedRecyclerView = "2.4.3"

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
aspectj = { id = "io.freefair.aspectj.android", version.ref = "freefairAspectj" }

[libraries]
# AndroidX 核心库
appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }

# getActivity 系列框架
xxPermissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xxPermissions" }
titleBar = { module = "com.github.getActivity:TitleBar", version.ref = "titleBar" }
toaster = { module = "com.github.getActivity:Toaster", version.ref = "toaster" }
easyHttp = { module = "com.github.getActivity:EasyHttp", version.ref = "easyHttp" }
gsonFactory = { module = "com.github.getActivity:GsonFactory", version.ref = "gsonFactory" }
shapeView = { module = "com.github.getActivity:ShapeView", version.ref = "shapeView" }

# 网络相关
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
okHttpSse = { module = "com.squareup.okhttp3:okhttp-sse", version.ref = "okHttp" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# 图片加载
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# UI 相关
immersionBar = { module = "com.geyifeng.immersionbar:immersionbar", version.ref = "immersionBar" }
photoView = { module = "com.github.Baseflow:PhotoView", version.ref = "photoView" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
refreshLayoutKernel = { module = "io.github.scwang90:refresh-layout-kernel", version.ref = "refreshLayout" }
refreshHeaderMaterial = { module = "io.github.scwang90:refresh-header-material", version.ref = "refreshLayout" }
circleIndicator = { module = "me.relex:circleindicator", version.ref = "circleIndicator" }
groupedRecyclerViewAdapter = { module = "com.github.donkingliang:GroupedRecyclerViewAdapter", version.ref = "groupedRecyclerView" }

# 工具类
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
mmkvStatic = { module = "com.tencent:mmkv-static", version.ref = "mmkv" }
utilCodex = { module = "com.blankj:utilcodex", version.ref = "utilCodex" }

# 异常捕捉
bugly = { module = "com.tencent.bugly:crashreport", version.ref = "bugly" }
buglyNative = { module = "com.tencent.bugly:nativecrashreport", version = "3.9.2" }

# 调试工具
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }

# AOP
aspectjrt = { module = "org.aspectj:aspectjrt", version.ref = "aspectj" }

# 数据库
greenDao = { module = "org.greenrobot:greendao", version.ref = "greenDao" }

# 安全加密
rsaUtils = { module = "com.github.gzu-liyujiang:RSAUtils", version.ref = "rsaUtils" }
bouncyCastle = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bouncyCastle" }

# Markdown 渲染
markwonCore = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwonHtml = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwonImage = { module = "io.noties.markwon:image", version.ref = "markwon" }
markwonLinkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
markwonStrikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
markwonTables = { module = "io.noties.markwon:ext-tables", version.ref = "markwon" }
markwonTasklist = { module = "io.noties.markwon:ext-tasklist", version.ref = "markwon" }
